#!/usr/bin/env bash
ln -sf eevee/{*.ml{,i},libmincaml.S} .
cd test; ln -sf eevee/{,too}manyargs.ml .; cd ..
cd shootout; ln -sf eevee/Makefile .; cd ..
cd bytemark; ln -sf eevee/Makefile .; cd ..
cd min-rt; ln -sf eevee/globals.s .; cd ..
